# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitebias_core', '0004_auto_20170507_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_of_clusters', models.PositiveIntegerField(default=2)),
                ('algorithm', models.CharField(choices=[('kmeans', 'K-Mneas')], default='kmeans', max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('index', models.PositiveIntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitebias_core.ClusterCriteria')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='sitebias_core.Organization')),
            ],
        ),
        migrations.AlterModelOptions(
            name='organizationfeature',
            options={'ordering': ('organization', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='clustercriteria',
            unique_together=set([('number_of_clusters', 'algorithm')]),
        ),
        migrations.AlterUniqueTogether(
            name='clusterlabel',
            unique_together=set([('criteria', 'organization', 'start_date', 'end_date', 'index')]),
        ),
    ]
