# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitebias_core', '0006_auto_20170507_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='clustercriteria',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('kmeans-even', 'K-Means-Even')], default='kmeans', max_length=50),
        ),
        migrations.AddField(
            model_name='clusterprior',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priors', to='sitebias_core.ClusterCriteria'),
        ),
        migrations.AddField(
            model_name='clusterprior',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priors', to='sitebias_core.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='clusterprior',
            unique_together=set([('criteria', 'organization')]),
        ),
    ]
