# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitebias_core', '0007_auto_20170508_0402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterprior',
            unique_together=set([('criteria', 'index')]),
        ),
    ]
