# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitebias_core', '0008_auto_20170508_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sitebias_core.ClusterCriteria')),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_links', to='sitebias_core.Organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='sitebias_core.Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clusterlink',
            unique_together=set([('criteria', 'from_organization', 'start_date', 'end_date', 'to_organization')]),
        ),
    ]
