# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebias_core', '0009_auto_20170514_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustercriteria',
            name='fresh',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='clustercriteria',
            name='term',
            field=models.CharField(blank=True, help_text='Term to calculate sentimate for. Only used for the Bayesian Sentiment algorithm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clusterlabel',
            name='fresh',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='clusterlabel',
            name='logprob',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='clusterlink',
            name='fresh',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='clusterprior',
            name='fresh',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='fresh',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='clustercriteria',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('kmeans-even', 'K-Means-Even'), ('bayesian-sentiment-nyt', 'Bayesian Sentiment (NYT)')], default='kmeans', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='clustercriteria',
            unique_together=set([('number_of_clusters', 'algorithm', 'term')]),
        ),
    ]
